spring.datasource.url=jdbc:sqlite:classlinker.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=
spring.sql.init.mode=always
spring.thymeleaf.cache=false
server.port=${PORT:8080}
spring.session.store-type=none
